services:
  client:
    container_name: frontend
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports: 
      - "8080:3000"
    depends_on:
      - server
    networks:
      - my_network
  server:
    container_name: backend
    build: ./server
    ports: 
    - "5001:5000"
    volumes:
      - ./server/info:/server/info
    networks:
      - my_network
    environment:
    - FLASK_DEBUG=1
    - OLLAMA_HOST=${OLLAMA_HOST}
  ai:
    container_name: ollamaAi
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - my_network
    volumes:
      - ollama_data:/root/.ollama
    

networks:
  my_network:
    driver: bridge

volumes:
  ollama_data:



