services:
  client:
    container_name: frontend
    build: ./client
    ports: 8080:3000
    depends_on:
      - server
  server:
    container_name: backend
    build: ./server
    ports: 5000:5000

networks:
  my_network:
    driver: bridge


